name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: set up JDK 11
      uses: actions/setup-java@v2.2.0
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    
    - name: Add GITHUB_CLIENT_ID
      run: echo "GITHUB_CLIENT_ID=\""${{ secrets.CLIENT_ID }}"\"" >> ./local.properties
      
    - name: Add GITHUB_CLIENT_SECRET
      run: echo "GITHUB_CLIENT_SECRET=\""${{ secrets.CLIENT_SECRET }}"\"" >> ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build release APK
      id: buildRelease
      run: bash ./gradlew assembleRelease --stacktrace
    
    - name: Sign APK
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}   
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/release/app-release-unsigned-signed.apk
